package cn.lambdacraft.mob.client.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

//Date: 2014/9/26 18:53:44
//Template version 1.1
//Java generated by Techne
//Keep in mind that you still need to fill in some blanks
//- ZeuX

public class ModelMobBull extends ModelBase {
	// fields
	ModelRenderer Shape1;
	ModelRenderer Shape2;
	ModelRenderer Shape3;
	ModelRenderer Shape4;
	ModelRenderer Shape5;
	ModelRenderer Shape6;
	ModelRenderer Shape7;
	ModelRenderer Shape8;
	ModelRenderer Shape9;
	ModelRenderer Shape10;
	ModelRenderer Shape11;
	ModelRenderer Shape12;
	ModelRenderer Shape13;
	ModelRenderer Shape14;
	ModelRenderer Shape15;

	public ModelMobBull() {
		textureWidth = 256;
		textureHeight = 128;

		Shape1 = new ModelRenderer(this, 35, 0);
		Shape1.addBox(-4F, -3F, 0F, 4, 6, 9);
		Shape1.setRotationPoint(-6F, 13F, 3F);
		Shape1.setTextureSize(256, 128);
		Shape1.mirror = true;
		setRotation(Shape1, -0.669215F, 0F, 0F);
		Shape2 = new ModelRenderer(this, 74, 0);
		Shape2.addBox(-5F, 0F, -5F, 9, 5, 6);
		Shape2.setRotationPoint(0F, 11F, -1F);
		Shape2.setTextureSize(256, 128);
		Shape2.mirror = true;
		setRotation(Shape2, 0.0371786F, 0F, 0F);
		Shape3 = new ModelRenderer(this, 0, 0);
		Shape3.addBox(0F, 0F, -8F, 1, 2, 9);
		Shape3.setRotationPoint(3F, 13F, -7F);
		Shape3.setTextureSize(256, 128);
		Shape3.mirror = true;
		setRotation(Shape3, 0.0371786F, -0.2974289F, 0F);
		Shape4 = new ModelRenderer(this, 32, 23);
		Shape4.addBox(0F, 0F, 0F, 7, 5, 8);
		Shape4.setRotationPoint(-4F, 11F, 12F);
		Shape4.setTextureSize(256, 128);
		Shape4.mirror = true;
		setRotation(Shape4, -0.1115358F, 0F, 0F);
		Shape5 = new ModelRenderer(this, 0, 50);
		Shape5.addBox(-2F, -2F, 0F, 5, 5, 9);
		Shape5.setRotationPoint(-1F, 14F, 19.4F);
		Shape5.setTextureSize(256, 128);
		Shape5.mirror = true;
		setRotation(Shape5, -0.4461433F, 0F, 0F);
		Shape6 = new ModelRenderer(this, 0, 75);
		Shape6.addBox(-1F, -1F, 0F, 3, 3, 10);
		Shape6.setRotationPoint(-1F, 17F, 26F);
		Shape6.setTextureSize(256, 128);
		Shape6.mirror = true;
		setRotation(Shape6, -0.2974289F, 0F, 0F);
		Shape15 = new ModelRenderer(this, 0, 0);
		Shape15.addBox(0F, 0F, -9F, 1, 2, 9);
		Shape15.setRotationPoint(-5F, 12.53333F, -6F);
		Shape15.setTextureSize(256, 128);
		Shape15.mirror = true;
		setRotation(Shape3, 0F, 0.3346075F, 0F);
		Shape7 = new ModelRenderer(this, 0, 0);
		Shape7.addBox(0F, 0F, -8F, 1, 2, 8);
		Shape7.setRotationPoint(-3F, 11F, -6F);
		Shape7.setTextureSize(256, 128);
		Shape7.mirror = true;
		setRotation(Shape7, 0F, 0F, 0F);
		Shape8 = new ModelRenderer(this, 0, 0);
		Shape8.addBox(0F, 0F, -8F, 1, 2, 8);
		Shape8.setRotationPoint(1F, 11F, -6F);
		Shape8.setTextureSize(256, 128);
		Shape8.mirror = true;
		setRotation(Shape7, 0F, 0F, 0F);
		Shape9 = new ModelRenderer(this, 0, 0);
		Shape9.addBox(0F, 0F, -8F, 1, 2, 10);
		Shape9.setRotationPoint(-1F, 12F, -8F);
		Shape9.setTextureSize(256, 128);
		Shape9.mirror = true;
		setRotation(Shape7, 0.1487144F, 0.0371786F, -0.1115358F);
		Shape10 = new ModelRenderer(this, 76, 24);
		Shape10.addBox(0F, 0F, -8F, 2, 2, 8);
		Shape10.setRotationPoint(-1F, 14F, -6F);
		Shape10.setTextureSize(256, 128);
		Shape10.mirror = true;
		setRotation(Shape7, 0.4461433F, 0.0371786F, -0.0371786F);
		Shape11 = new ModelRenderer(this, 114, 0);
		Shape11.addBox(-4F, 0F, 0F, 11, 6, 12);
		Shape11.setRotationPoint(-2F, 10F, 0F);
		Shape11.setTextureSize(256, 128);
		Shape11.mirror = true;
		setRotation(Shape1, -0.0349066F, 0F, 0F);
		Shape12 = new ModelRenderer(this, 0, 23);
		Shape12.addBox(-1F, -2F, 0F, 3, 3, 11);
		Shape12.setRotationPoint(-8F, 20F, 10F);
		Shape12.setTextureSize(256, 128);
		Shape12.mirror = true;
		setRotation(Shape1, -2.9557F, 0F, 0F);
		Shape13 = new ModelRenderer(this, 35, 0);
		Shape13.addBox(-4F, -3F, 0F, 4, 6, 9);
		Shape13.setRotationPoint(9F, 13F, 3F);
		Shape13.setTextureSize(256, 128);
		Shape13.mirror = true;
		setRotation(Shape1, -0.669215F, 0F, 0F);
		Shape14 = new ModelRenderer(this, 0, 23);
		Shape14.addBox(-1F, -2F, 0F, 3, 3, 11);
		Shape14.setRotationPoint(6F, 20F, 10F);
		Shape14.setTextureSize(256, 128);
		Shape14.mirror = true;
		setRotation(Shape1, -2.9557F, 0F, 0F);
	}

	public void render(Entity entity, float f, float f1, float f2, float f3,
			float f4, float f5) {
		super.render(entity, f, f1, f2, f3, f4, f5);
		setRotationAngles(f, f1, f2, f3, f4, f5, entity);
		Shape1.render(f5);
		Shape2.render(f5);
		Shape3.render(f5);
		Shape4.render(f5);
		Shape5.render(f5);
		Shape6.render(f5);
		Shape7.render(f5);
		Shape8.render(f5);
		Shape9.render(f5);
		Shape10.render(f5);
		Shape11.render(f5);
		Shape12.render(f5);
		Shape13.render(f5);
		Shape14.render(f5);
		Shape15.render(f5);
	}

	private void setRotation(ModelRenderer model, float x, float y, float z) {
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}

	public void setRotationAngles(float f, float f1, float f2, float f3,
			float f4, float f5, Entity entity) {
		super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
	}

}
